### PR TITLE
Add SONiC testbed docs

### PR DESCRIPTION
**Pull request by matofeder**
* This PR adds a tutorial that walks you through setting up and configuring a basic testbed environment in the GNS3 simulation platform. The setup includes three SONiC switches (Spline, Leaf1, Leaf2) with community images and two PCs connected to Leaf1 and Leaf2. 
  * The guide also covers a basic BGP L3 underlay configuration using FRR.
* This PR moves some general SONiC docs into a separate file under the docs directory

@scoopex I just wanted to push my test environment docs to the repo, as I always prefer to have the possibility to develop things locally. Netbox, ansible thing is ongoing and I'm testing it with the provided SONiC testbed env. 

relates to https://github.com/SovereignCloudStack/issues/issues/538

### CODE REVIEW

**Comment by berendt** [comment]
I think it makes more sense to add this docs to https://github.com/sovereigncloudstack/docs ?

**Comment by matofeder** [comment]
> I think it makes more sense to add this docs to https://github.com/sovereigncloudstack/docs ?

I agree that landscape-related docs should be visible at https://docs.scs.community/

AFAIK The recommended way is to reference the repository docs files in the SCS docs repository. See e.g. https://github.com/SovereignCloudStack/docs/pull/144

**Comment by scoopex** [comment]
> I think it makes more sense to add this docs to https://github.com/sovereigncloudstack/docs ?

Sure, lets discuss that with @maxwolfs to have a SONiC Section in the documentation.

**Review by scoopex — APPROVED** [review]
LGTM

**Pull request merged**
